name: shadowdom_teacher
version: 0.0.1
author: Name It Later
description: Teach bootstrap, flat_ui, and font-awesome to use shadowdom.
homepage: https://www.github.com/nameitlater/shadowdom-teacher
dependencies:
  args: '>=0.9.0 <0.10.0'
  csslib: '>=0.9.2 < 0.10.0'
